name: Fly Deploy (Frontend)
on:
  push:
    branches:
      - main
    paths:
      - frontend/**
jobs:
  deploy:
    name: Deploy frontend
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: "frontend"
          sparse-checkout-cone-mode: false

      - name: Move frontend files to root
        run: |
          ls -lah
          mv frontend/* .
          rm -rf frontend
          ls -lah

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FRONTEND_FLY_TOKEN }}
