name: Deploy DB migrations
on:
  push:
    branches:
      - main
    paths:
      - backend/prisma/**
jobs:
  deploy:
    name: Deploy DB migrations
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: "backend"
          sparse-checkout-cone-mode: false

      - name: Move backend files to root
        run: |
          ls -lah
          mv backend/* .
          rm -rf backend
          ls -lah

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          npm ci
          npm run build
      # - name: Populate env file
      #   run: |
      #     echo "_DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" > .env

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl proxy 15432:5432 -a fnz &
          sleep 5
          npx prisma migrate deploy
          pkill fly
        env:
          FLY_API_TOKEN: ${{ secrets.DB_FLY_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
